apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" , }}
  namespace: remkohdev-ns
  labels:
    app: {{ template "name" , }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fdic-api
  template:
    metadata:
{{ - if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{ - end }}
      labels:
        app: fdic-api
    spec:
      containers:
      - name: fdic-api
        image: registry.ng.bluemix.net/remkohdev-ns/fdic-api:latest
        ports:
        - name: http
          protocol: TCP
          containerPort: 3000
        env:
        - name: COUCHDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchdb-credentials
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-credentials
              key: password
        envFrom:
        - configMapRef:
            name: fdic-api-configmap
      imagePullSecrets:
      - name: bluemix-remkohdev-ns-secret