---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: couchdb-hpa
  namespace: remkohdev-ns
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: couchdb-deployment
  targetCPUUtilizationPercentage: 80