---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-svc
  namespace: remkohdev-ns
  labels:
    app: couchdb
spec:
  type: NodePort
  ports:
  - name: couchdb
    protocol: TCP
    port: 5984
    targetPort: 5984
  selector: 
    app: couchdb