---
apiVersion: v1
kind: Service
metadata:
  name: fdic-api-svc
  namespace: remkohdev-ns
  labels:
    app: fdic-api
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: fdic-api